name: build-and-deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # ---------- GIT ----------
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- DOCKER LOGIN ----------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # ---------- BUILD IMAGE ----------
      - name: Build Docker image
        run: docker build -t aurait/backend-demo:latest .

      - name: Push Docker image
        run: docker push aurait/backend-demo:latest

      # ---------- PREPARE KUBECONFIG ----------
      - name: Generate kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Set kubeconfig
        run: |
          export KUBECONFIG=$HOME/.kube/config
          echo "KUBECONFIG is set to: $KUBECONFIG"

      # ---------- TEST K8S CONNECTION ----------
      - name: Test kubectl access
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl get nodes

      # ---------- DEPLOY ----------
      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl apply -f k8s/backend-deployment.yaml --validate=false
          kubectl apply -f k8s/backend-service.yaml --validate=false

      # ---------- CHECK ROLLOUT ----------
      - name: Check rollout
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl rollout status deployment/backend-demo
